# Generated by Django 6.0.4 on 2026-05-29 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_alter_endpoint_is_active_alter_ipaddress_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorcheck',
            name='response_time_ms',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monitorcheck',
            name='status',
            field=models.CharField(choices=[('UP', 'UP'), ('DOWN', 'DOWN')], max_length=10),
        ),
    ]
