# Generated by Django 6.0.4 on 2026-05-30 18:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_alter_monitorcheck_response_time_ms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='timeout_seconds',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='timeout_seconds',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
