# Generated by Django 6.0.4 on 2026-05-31 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_alter_endpoint_timeout_seconds_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.DateTimeField()),
                ('total_checks', models.IntegerField()),
                ('up_count', models.IntegerField()),
                ('down_count', models.IntegerField()),
                ('avg_response_time_ms', models.FloatField()),
                ('uptime_percent', models.FloatField()),
                ('endpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoring.endpoint')),
                ('ip_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoring.ipaddress')),
            ],
            options={
                'indexes': [models.Index(fields=['endpoint', 'ip_address', 'hour'], name='monitoring__endpoin_259fb7_idx')],
                'unique_together': {('endpoint', 'ip_address', 'hour')},
            },
        ),
    ]
