# Generated by Django 6.0.4 on 2026-05-31 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_hourlystats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='dailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('IP', 'IP Address'), ('ENDPOINT', 'Endpoint')], max_length=10)),
                ('day', models.DateTimeField()),
                ('total_checks', models.IntegerField()),
                ('up_count', models.IntegerField()),
                ('down_count', models.IntegerField()),
                ('avg_response_time_ms', models.FloatField()),
                ('uptime_percent', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='HourlyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('IP', 'IP Address'), ('ENDPOINT', 'Endpoint')], max_length=10)),
                ('hour', models.DateTimeField()),
                ('total_checks', models.IntegerField()),
                ('up_count', models.IntegerField()),
                ('down_count', models.IntegerField()),
                ('avg_response_time_ms', models.FloatField()),
                ('uptime_percent', models.FloatField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='hourlystats',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='hourlystats',
            name='monitoring__endpoin_259fb7_idx',
        ),
        migrations.AddField(
            model_name='dailystat',
            name='endpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoring.endpoint'),
        ),
        migrations.AddField(
            model_name='dailystat',
            name='ip_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoring.ipaddress'),
        ),
        migrations.AddField(
            model_name='dailystat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hourlystat',
            name='endpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoring.endpoint'),
        ),
        migrations.AddField(
            model_name='hourlystat',
            name='ip_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoring.ipaddress'),
        ),
        migrations.AddField(
            model_name='hourlystat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_stats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='hourlystats',
            name='endpoint',
        ),
        migrations.RemoveField(
            model_name='hourlystats',
            name='ip_address',
        ),
        migrations.AddIndex(
            model_name='dailystat',
            index=models.Index(fields=['ip_address', 'day'], name='monitoring__ip_addr_e03db6_idx'),
        ),
        migrations.AddIndex(
            model_name='dailystat',
            index=models.Index(fields=['endpoint', 'day'], name='monitoring__endpoin_486147_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailystat',
            constraint=models.UniqueConstraint(condition=models.Q(('ip_address__isnull', False)), fields=('ip_address', 'day'), name='unique_ip_day'),
        ),
        migrations.AddConstraint(
            model_name='dailystat',
            constraint=models.UniqueConstraint(condition=models.Q(('endpoint__isnull', False)), fields=('endpoint', 'day'), name='unique_endpoint_day'),
        ),
        migrations.AddIndex(
            model_name='hourlystat',
            index=models.Index(fields=['ip_address', 'hour'], name='monitoring__ip_addr_f603f9_idx'),
        ),
        migrations.AddIndex(
            model_name='hourlystat',
            index=models.Index(fields=['endpoint', 'hour'], name='monitoring__endpoin_68ebcb_idx'),
        ),
        migrations.AddConstraint(
            model_name='hourlystat',
            constraint=models.UniqueConstraint(condition=models.Q(('ip_address__isnull', False)), fields=('ip_address', 'hour'), name='unique_ip_hour'),
        ),
        migrations.AddConstraint(
            model_name='hourlystat',
            constraint=models.UniqueConstraint(condition=models.Q(('endpoint__isnull', False)), fields=('endpoint', 'hour'), name='unique_endpoint_hour'),
        ),
        migrations.DeleteModel(
            name='HourlyStats',
        ),
    ]
