# Generated by Django 6.0.4 on 2026-06-04 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipaddress',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'IP Addresses'},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name_plural': 'Settings'},
        ),
    ]
