# Generated by Django 6.0.4 on 2026-06-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0009_alter_ipaddress_options_alter_settings_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='webhook_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
